version: '1.0'

networks:
  default:
    driver: bridge
services:
  api:
    build: .
    depends_on:
      - db
      - pg_admin
    networks:
      - default
    volumes:
      - ./app:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5000:5000"
    env_file:
      - db.env

  db:
    image: postgres
    restart: no
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
    - "5432:5432"

  pg_admin:
    image: dpage/pgadmin4
    restart: no
    ports:
      - "9001:80"
    env_file:
      - pg_admin.env
    volumes:
      - pg_admin_data:/var/lib/pg_admin/data

volumes:
  pg_admin_data:
  db_data:
